In [48]:
import pickle
from tensorflow.keras.models import load_model

kaggle_model = load_model("kaggle_text_model.keras")
trap_model = load_model("trap4phish_model.keras")
spam_model = load_model("spamassassin_model.keras")

with open("kaggle_tokenizer.pkl", "rb") as f:
    kaggle_tokenizer = pickle.load(f)

with open("spamassassin_tokenizer.pkl", "rb") as f:
    spam_tokenizer = pickle.load(f)

with open("trap4phish_scaler.pkl", "rb") as f:
    trap_scaler = pickle.load(f)

print("All models and preprocessing files loaded successfully.")

/home/moaz/projects/Email forensics/.venv/lib/python3.12/site-packages/keras/src/saving/saving_lib.py:801: UserWarning: Skipping variable loading for optimizer 'adam', because it has 14 variables whereas the saved optimizer has 2 variables.
  saveable.load_own_variables(weights_store.get(inner_path))
/home/moaz/projects/Email forensics/.venv/lib/python3.12/site-packages/keras/src/saving/saving_lib.py:801: UserWarning: Skipping variable loading for optimizer 'adam', because it has 24 variables whereas the saved optimizer has 2 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

All models and preprocessing files loaded successfully.

In [49]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [50]:
def predict_kaggle_email(email_text):
    seq = kaggle_tokenizer.texts_to_sequences([email_text])
    padded = pad_sequences(seq, maxlen=200)
    prob = float(kaggle_model.predict(padded)[0][0])
    if prob >= 0.5:
        label = "Phishing"
    else:
        label = "Legitimate"
    return {
        "model": "Kaggle Phishing Model",
        "prediction": label,
        "confidence_score": prob
    }

In [51]:

sample_email = "Your account has been suspended. Click this link immediately to verify your password."
predict_kaggle_email(sample_email)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 486ms/step

{'model': 'Kaggle Phishing Model',
 'prediction': 'Phishing',
 'confidence_score': 0.5061964988708496}

In [52]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [53]:
def predict_spamassassin_email(email_text):
    seq = spam_tokenizer.texts_to_sequences([email_text])
    padded = pad_sequences(seq, maxlen=200)
    prob = float(spam_model.predict(padded)[0][0])
    if prob >= 0.5:
        label = "Spam/Phishing"
    else:
        label = "Legitimate"
    return {
        "model": "SpamAssassin Model",
        "prediction": label,
        "confidence_score": prob
    }

In [54]:
predict_spamassassin_email(sample_email)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 492ms/step

{'model': 'SpamAssassin Model',
 'prediction': 'Legitimate',
 'confidence_score': 0.49994370341300964}

## Trap4Phish Integration

Trap4Phish uses spreadsheet/macro-based numerical features, so a real Trap4Phish feature vector is used for integration testing. Raw SpamAssassin emails do not contain these spreadsheet feature values directly.

In [55]:
import pandas as pd

def predict_trap4phish(features):

    features_df = pd.DataFrame(
        [features],
        columns=trap_scaler.feature_names_in_
    )

    features_scaled = trap_scaler.transform(features_df)

    prob = float(trap_model.predict(features_scaled)[0][0])

    if prob >= 0.5:
        label = "Phishing"
    else:
        label = "Legitimate"

    return {
        "model": "Trap4Phish Model",
        "prediction": label,
        "confidence_score": prob
    }

In [33]:
sample_features = [0.2] * 10
predict_trap4phish(sample_features)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

{'model': 'Trap4Phish Model',
 'prediction': 'Legitimate',
 'confidence_score': 0.49498695135116577}

In [100]:
def analyze_email_text(email_text, trap_features=None):
    kaggle_result = predict_kaggle_email(email_text)
    spam_result = predict_spamassassin_email(email_text)

    results = {
        "email_text": email_text,
        "kaggle_model_result": kaggle_result,
        "spamassassin_model_result": spam_result
    }

    if trap_features is not None:
        trap_result = predict_trap4phish(trap_features)
        results["trap4phish_model_result"] = trap_result
    else:
        trap_result = None

    phishing_votes = 0
    legitimate_votes = 0
    borderline_models = []

    # Kaggle vote
    if kaggle_result["prediction"] == "Phishing":
        phishing_votes += 1
    else:
        legitimate_votes += 1

    if 0.45 <= kaggle_result["confidence_score"] <= 0.55:
        borderline_models.append("Kaggle")

    # SpamAssassin vote
    if spam_result["prediction"] == "Spam/Phishing":
        phishing_votes += 1
    else:
        legitimate_votes += 1

    if 0.45 <= spam_result["confidence_score"] <= 0.55:
        borderline_models.append("SpamAssassin")

    # Trap4Phish vote
    if trap_result is not None:
        if trap_result["prediction"] == "Phishing":
            phishing_votes += 1
        else:
            legitimate_votes += 1

        if 0.45 <= trap_result["confidence_score"] <= 0.55:
            borderline_models.append("Trap4Phish")

    # Majority vote final verdict
    if phishing_votes > legitimate_votes:
        final_verdict = "Suspicious / Potential Phishing"
    elif legitimate_votes > phishing_votes:
        final_verdict = "Likely Legitimate"
    else:
        final_verdict = "Requires Manual Review"

    results["phishing_votes"] = phishing_votes
    results["legitimate_votes"] = legitimate_votes
    results["borderline_models"] = borderline_models
    results["final_verdict"] = final_verdict

    return results

In [101]:
analyze_email_text(sample_email)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step

{'email_text': 'Your account has been suspended. Click this link immediately to verify your password.',
 'kaggle_model_result': {'model': 'Kaggle Phishing Model',
  'prediction': 'Phishing',
  'confidence_score': 0.5061964988708496},
 'spamassassin_model_result': {'model': 'SpamAssassin Model',
  'prediction': 'Legitimate',
  'confidence_score': 0.49994370341300964},
 'phishing_votes': 1,
 'legitimate_votes': 1,
 'borderline_models': ['Kaggle', 'SpamAssassin'],
 'final_verdict': 'Requires Manual Review'}

In [57]:
def generate_forensic_report(email_text):
    analysis = analyze_email_text(email_text)
    print("====== EMAIL FORENSIC REPORT ======")
    print()
    print("Email Content:")
    print(email_text)
    print()
    print("Kaggle Model Prediction:")
    print(analysis["kaggle_model_result"])
    print()
    print("SpamAssassin Model Prediction:")
    print(analysis["spamassassin_model_result"])
    print()
    print("Final Verdict:")
    print(analysis["final_verdict"])

In [37]:
generate_forensic_report(sample_email)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
====== EMAIL FORENSIC REPORT ======

Email Content:
Your account has been suspended. Click this link immediately to verify your password.

Kaggle Model Prediction:
{'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5061964988708496}

SpamAssassin Model Prediction:
{'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.49994370341300964}

Final Verdict:
Suspicious / Potential Phishing

In [58]:
def generate_full_report(email_text, trap_features=None):
    text_analysis = analyze_email_text(email_text)
    print("====== EMAIL FORENSIC REPORT ======")
    print("Email Content:")
    print(email_text)
    print()
    print("Kaggle Model Prediction:")
    print(text_analysis["kaggle_model_result"])
    print()
    print("SpamAssassin Model Prediction:")
    print(text_analysis["spamassassin_model_result"])
    print()
    if trap_features is not None:
        trap_result = predict_trap4phish(trap_features)
        print("Trap4Phish Model Prediction:")
        print(trap_result)
        print()
    print("Final Verdict:")
    print(text_analysis["final_verdict"])

In [88]:
generate_full_report(sample_email, sample_features)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
====== EMAIL FORENSIC REPORT ======
Email Content:
Your account has been suspended. Click this link immediately to verify your password.

Kaggle Model Prediction:
{'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5061964988708496}

SpamAssassin Model Prediction:
{'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.49994370341300964}

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Trap4Phish Model Prediction:
{'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}

Final Verdict:
Requires Manual Review

In [60]:
from email import message_from_string
from email.policy import default

def parse_email(raw_email):
    msg = message_from_string(raw_email, policy=default)

    parsed_data = {
        "from": msg.get("From"),
        "to": msg.get("To"),
        "subject": msg.get("Subject"),
        "date": msg.get("Date"),
        "return_path": msg.get("Return-Path"),
        "received_headers": msg.get_all("Received", []),
        "authentication_results": msg.get("Authentication-Results")
    }

    return parsed_data

In [43]:
email_path = "Datasets/spamassassin/20021010_spam/spam/0498.863566df8e5f17f979edca79d1e87187"

with open(email_path, "r", encoding="latin-1") as f:
    raw_email = f.read()

parse_email(raw_email)

{'from': 'Answer.Us@davicom.co.kr',
 'to': 'undisclosed-recipients:;',
 'subject': '$10 a hour for watching e-mmercials! No joke!',
 'date': 'Mon, 07 Oct 2002 22:57:45 -0400',
 'return_path': '<bounce2@u-answer.com>',
 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby zzzzason.org (Postfix) with ESMTP id 10C9616F18\tfor <zzzz@localhost>; Tue,  8 Oct 2002 11:02:05 +0100 (IST)',
  'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Tue, 08 Oct 2002 11:02:05 +0100 (IST)',
  'from webnote.net (mail.webnote.net [193.120.211.219]) by    dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g98339K30569 for    <zzzz@jmason.org>; Tue, 8 Oct 2002 04:03:10 +0100',
  'from davicom.co.kr (IDENT:root@[211.205.76.5]) by webnote.net    (8.9.3/8.9.3) with ESMTP id EAA21173 for <zzzz@example.com>;    Tue, 8 Oct 2002 04:03:55 +0100',
  'from u-answer.com (kenny.answer-us.com [12.43.213.7]) by    davicom.co.kr (v3smtp 8.11.2 Copyright (c) 1998-2000 Sendmail,    Inc.  All rights reserved. Copyright (c) 1988, 1993 The Regents of the    University of California.  All rights reserved./8.11.3) with ESMTP id    g983Hsn28746; Tue, 8 Oct 2002 12:17:55 +0900'],
 'authentication_results': None}

In [61]:
def analyze_headers(parsed_email):
    findings = []
    if parsed_email["return_path"]:
        findings.append("Return-Path found")
    if parsed_email["received_headers"]:
        findings.append(f"{len(parsed_email['received_headers'])} Received headers detected")
    if parsed_email["authentication_results"] is None:
        findings.append("No SPF/DKIM/DMARC authentication results present")
    return findings

In [45]:
parsed_email = parse_email(raw_email)
analyze_headers(parsed_email)

['Return-Path found',
 '5 Received headers detected',
 'No SPF/DKIM/DMARC authentication results present']

In [102]:
def generate_integrated_report(raw_email, trap_features=None):
    parsed_email = parse_email(raw_email)
    header_findings = analyze_headers(parsed_email)

    email_text = clean_email_body(raw_email)
    ml_analysis = analyze_email_text(email_text, trap_features)

    print("====== INTEGRATED EMAIL FORENSIC REPORT ======\n")

    print("--- Parsed Email Details ---")
    print("From:", parsed_email.get("from"))
    print("To:", parsed_email.get("to"))
    print("Subject:", parsed_email.get("subject"))
    print("Date:", parsed_email.get("date"))
    print("Return-Path:", parsed_email.get("return_path"))

    print("\n--- Header Analysis Findings ---")
    for finding in header_findings:
        print("-", finding)

    print("\n--- ML Detection Results ---")
    kaggle = ml_analysis["kaggle_model_result"]
    spamassassin = ml_analysis["spamassassin_model_result"]

    print("Kaggle Model:", kaggle["prediction"], "| Score:", round(kaggle["confidence_score"], 4))
    print("SpamAssassin Model:", spamassassin["prediction"], "| Score:", round(spamassassin["confidence_score"], 4))

    if "trap4phish_model_result" in ml_analysis:
        trap = ml_analysis["trap4phish_model_result"]
        print("Trap4Phish Model:", trap["prediction"], "| Score:", round(trap["confidence_score"], 4))

    print("\n--- Decision Summary ---")
    print("Phishing Votes:", ml_analysis["phishing_votes"])
    print("Legitimate Votes:", ml_analysis["legitimate_votes"])
    print("Borderline Models:", ml_analysis["borderline_models"])

    print("\n--- Final Verdict ---")
    print(ml_analysis["final_verdict"])

    return ml_analysis

In [103]:
report = generate_integrated_report(raw_email, sample_features)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

--- Parsed Email Details ---
From: Answer.Us@davicom.co.kr
To: undisclosed-recipients:;
Subject: $10 a hour for watching e-mmercials! No joke!
Date: Mon, 07 Oct 2002 22:57:45 -0400
Return-Path: <bounce2@u-answer.com>

--- Header Analysis Findings ---
- Return-Path found
- 5 Received headers detected
- No SPF/DKIM/DMARC authentication results present

--- ML Detection Results ---
Kaggle Model: Phishing | Score: 0.5054
SpamAssassin Model: Legitimate | Score: 0.4967
Trap4Phish Model: Legitimate | Score: 0.495

--- Decision Summary ---
Phishing Votes: 1
Legitimate Votes: 2
Borderline Models: ['Kaggle', 'SpamAssassin', 'Trap4Phish']

--- Final Verdict ---
Likely Legitimate

In [72]:
from email import policy
from email.parser import Parser

def extract_email_body(raw_email):
    msg = Parser(policy=policy.default).parsestr(raw_email)

    if msg.is_multipart():
        for part in msg.walk():
            content_type = part.get_content_type()

            if content_type == "text/plain":
                try:
                    return part.get_content()
                except:
                    payload = part.get_payload(decode=True)
                    return payload.decode("latin-1", errors="ignore")

            if content_type == "text/html":
                try:
                    return part.get_content()
                except:
                    payload = part.get_payload(decode=True)
                    return payload.decode("latin-1", errors="ignore")

    else:
        try:
            return msg.get_content()
        except:
            payload = msg.get_payload(decode=True)
            if payload:
                return payload.decode("latin-1", errors="ignore")
            return str(msg.get_payload())

    return ""

In [ ]:
email_body = extract_email_body(raw_email)
print(email_body[:1000])

PROFESSIONAL, EFFECTIVE DEBT COLLECTION SERVICES AVAILABLE

For the last seventeen years, National Credit Systems, Inc. has been providing
top flight debt collection services to over 15,000 businesses, institutions, and
healthcare providers.

We charge only a low-flat fee (less than $20) per account, and all proceeds are
forwarded to you directly -- not to your collections agency.

If you wish, we will report unpaid accounts to Experian (formerly TRW),
TRANSUNION, and Equifax. There is no charge for this important service.

PLEASE LET US KNOW IF WE CAN BE OF SERVICE TO YOU.

Simply reply to debt_collectors@chmailnet.com with the following instructions
in the Subject field -

REMOVE  --  Please remove me from your mailing list.
EMAIL   --  Please email more information.
FAX     --  Please fax more information.
MAIL    --  Please snailmail more information.
CALL    --  Please have a representative call.

Indicate the best time to telephone and any necessary addresses and
telephone/

In [ ]:
import subprocess
subprocess.check_call(["pip", "install", "beautifulsoup4"])

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in ./.venv/lib/python3.12/site-packages (from beautifulsoup4) (4.15.0)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.7/107.7 kB 1.0 MB/s eta 0:00:00a 0:00:01m
Downloading soupsieve-2.8.3-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4
Successfully installed beautifulsoup4-4.14.3 soupsieve-2.8.3

0

In [73]:
from bs4 import BeautifulSoup
def clean_email_body(raw_email):
    body = extract_email_body(raw_email)
    soup = BeautifulSoup(body, "html.parser")
    clean_text = soup.get_text(separator=" ", strip=True)
    return clean_text

In [74]:
clean_body = clean_email_body(raw_email)
print(clean_body[:1000])

Answer-Us Unlist Information This message is brought to you by Answer-us.com in
		compliance with current federal laws. To find out more about Answer-us.com visit http://www.answer-us.com .
        You are receiving this mailing because you or someone you know has
        registered this email address to receive special offers from an Answer-us.com
        marketing partner. Screening of addresses has been done to the best of
        our knowledge. We honor all unlist requests within 72 hours. If you
        have received this email in error, we apologize for any inconvenience it
        has caused and will not mail further offers to you. To be
        unlisted from our database, please do the
        following: Simply click here . If you have your mail forwarded to a new email address
        please provide your old email address. A nswer - Us Nationwide support@answer-us.com Our
        E-Mail Campaigns Have Produced
      Staggering Response Rates! Responsive
      General

In [ ]:
print(clean_email_body(raw_email)[:300])

PROFESSIONAL, EFFECTIVE DEBT COLLECTION SERVICES AVAILABLE

For the last seventeen years, National Credit Systems, Inc. has been providing
top flight debt collection services to over 15,000 businesses, institutions, and
healthcare providers.

We charge only a low-flat fee (less than $20) per accoun

## Integrated Email Forensic Analysis Pipeline

This module integrates email parsing, header analysis, machine learning-based phishing detection, and forensic verdict generation into a single investigation workflow.

In [ ]:
def generate_integrated_report(raw_email, trap_features=None):
    parsed_email = parse_email(raw_email)
    header_findings = analyze_headers(parsed_email)
    email_text = clean_email_body
    print("====== INTEGRATED EMAIL FORENSIC REPORT ======")
    print("\n--- Parsed Email Details ---")
    print("From:", parsed_email["from"])
    print("To:", parsed_email["to"])
    print("Subject:", parsed_email["subject"])
    print("Date:", parsed_email["date"])
    print("Return-Path:", parsed_email["return_path"])
    print("\n--- Header Analysis Findings ---")
    for finding in header_findings:
        print("-", finding)
    print("\n--- ML Detection Results ---")
    print("Kaggle:", ml_analysis["kaggle_model_result"]["prediction"],
          "| Score:", ml_analysis["kaggle_model_result"]["confidence_score"])
    print("SpamAssassin:", ml_analysis["spamassassin_model_result"]["prediction"],
          "| Score:", ml_analysis["spamassassin_model_result"]["confidence_score"])
    if "trap4phish_model_result" in ml_analysis:
        print("Trap4Phish:", ml_analysis["trap4phish_model_result"]["prediction"],
              "| Score:", ml_analysis["trap4phish_model_result"]["confidence_score"])
    print("\n--- Final Verdict ---")
    print(ml_analysis["final_verdict"])

In [ ]:
generate_integrated_report(raw_email, sample_features)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

--- Parsed Email Details ---
From: Answer.Us@davicom.co.kr
To: undisclosed-recipients:;
Subject: $10 a hour for watching e-mmercials! No joke!
Date: Mon, 07 Oct 2002 22:57:45 -0400
Return-Path: <bounce2@u-answer.com>

--- Header Analysis Findings ---
- Return-Path found
- 5 Received headers detected
- No SPF/DKIM/DMARC authentication results present

--- ML Detection Results ---
Kaggle: Phishing | Score: 0.5053941607475281
SpamAssassin: Legitimate | Score: 0.49671536684036255
Trap4Phish: Legitimate | Score: 0.49498695135116577

--- Final Verdict ---
Suspicious / Potential Phishing

In [ ]:
import pandas as pd

trap_df = pd.read_csv("Datasets/Trap4phish/Trap4phish.csv")
trap_df.head()

,file_name,entropy_of_text,macro_chr_count,macro_vocab_size,macro_arithmetic_operator_count,macro_token_count,macro_max_line_length,remote_template_present,numeric_cell_count,string_cell_count,avg_cell_length,label
0,benign_sample_3253.xlsx,5.746068,39,10079,4759,10079,38,1,4336,8926,11.184588,0
1,benign_sample_5685.xlsx,5.749956,287,19789,28783,19789,42,1,27138,54355,11.167818,0
2,benign_sample_8732.xlsx,5.745470,122,16084,12754,16084,38,1,12033,23997,11.132195,0
3,benign_sample_5743.xlsx,5.743675,152,17382,16244,17382,39,1,15217,30554,11.104673,0
4,benign_sample_5522.xlsx,5.748130,106,15452,11529,15452,38,1,10837,21622,11.151976,0

In [ ]:
trap_df.columns

Index(['file_name', 'entropy_of_text', 'macro_chr_count', 'macro_vocab_size',
       'macro_arithmetic_operator_count', 'macro_token_count',
       'macro_max_line_length', 'remote_template_present',
       'numeric_cell_count', 'string_cell_count', 'avg_cell_length', 'label'],
      dtype='str')

In [ ]:
feature_cols = [
    "entropy_of_text",
    "macro_chr_count",
    "macro_vocab_size",
    "macro_arithmetic_operator_count",
    "macro_token_count",
    "macro_max_line_length",
    "remote_template_present",
    "numeric_cell_count",
    "string_cell_count",
    "avg_cell_length"
]

sample_features = trap_df.loc[0, feature_cols].tolist()

sample_features

[5.746067900571417,
 39.0,
 10079.0,
 4759.0,
 10079.0,
 38.0,
 1.0,
 4336.0,
 8926.0,
 11.18458754335696]

In [ ]:
type(trap_scaler)

sklearn.preprocessing._data.StandardScaler

In [ ]:
trap_scaler.feature_names_in_

array(['entropy_of_text', 'macro_chr_count', 'macro_vocab_size',
       'macro_arithmetic_operator_count', 'macro_token_count',
       'macro_max_line_length', 'remote_template_present',
       'numeric_cell_count', 'string_cell_count', 'avg_cell_length'],
      dtype=object)

In [ ]:
import os

spam_folder = "Datasets/spamassassin/20021010_spam/spam"

print("Total spam emails:", len(os.listdir(spam_folder)))

Total spam emails: 501

In [ ]:
spam_files = os.listdir(spam_folder)[:5]

for file in spam_files:
    print("\n==============================")
    print("Testing file:", file)

    email_path = os.path.join(spam_folder, file)

    with open(email_path, "r", encoding="latin-1") as f:
        raw_email = f.read()

    generate_integrated_report(raw_email, sample_features)

==============================
Testing file: 0397.c02eba1386b00d640c954e5117dd1aa0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

--- Parsed Email Details ---
From: sunday68@bluemail.dk
To: paulifree@hotmail.com
Subject: FORTUNE 500 WORK AT HOME REPS NEEDED!
Date: Fri, 20 Sep 2002 04:47:45 +0100
Return-Path: <sunday68@bluemail.dk>

--- Header Analysis Findings ---
- Return-Path found
- 4 Received headers detected
- No SPF/DKIM/DMARC authentication results present

--- ML Detection Results ---
Kaggle: Phishing | Score: 0.5032728314399719
SpamAssassin: Legitimate | Score: 0.4946371018886566
Trap4Phish: Legitimate | Score: 0.49498695135116577

--- Final Verdict ---
Suspicious / Potential Phishing

==============================
Testing file: 0259.7ebf3c0fd752bce5b8056e9454d2c76f
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

--- Parsed Email Details ---
From: pamela4701@eudoramail.com
To: Undisclosed.Recipients@smtp-ft1.fr.colt.net
Subject: Let us find the right mortgage lender for you      AFPE
Date: Mon, 09 Sep 2002 14:36:18 -0700
Return-Path: <pamela4701@eudoramail.com>

--- Header Analysis Findings ---
- Return-Path found
- 5 Received headers detected
- No SPF/DKIM/DMARC authentication results present

--- ML Detection Results ---
Kaggle: Legitimate | Score: 0.49938228726387024
SpamAssassin: Legitimate | Score: 0.4973808228969574
Trap4Phish: Legitimate | Score: 0.49498695135116577

--- Final Verdict ---
Likely Legitimate

==============================
Testing file: 0114.c104ada3a249e1e1846c0cd156a303e9
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

--- Parsed Email Details ---
From: Free xxx movie <thisisagreatfreepornmovie@framesetup.com>
To: zzzz@example.com
Subject: 60 minute free porn movie
Date: Mon, 26 Aug 2002 22:18:15 -0400
Return-Path: <thisisagreatfreepornmovie@framesetup.com>

--- Header Analysis Findings ---
- Return-Path found
- 3 Received headers detected
- No SPF/DKIM/DMARC authentication results present

--- ML Detection Results ---
Kaggle: Phishing | Score: 0.5031223297119141
SpamAssassin: Legitimate | Score: 0.49444079399108887
Trap4Phish: Legitimate | Score: 0.49498695135116577

--- Final Verdict ---
Suspicious / Potential Phishing

==============================
Testing file: 0480.fc9323682825f7d93ed78a82970ceaea
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

--- Parsed Email Details ---
From: firstever001@top10.bestoffersonthenet.com
To: yziubpzytm@top10.bestoffersonthenet.com
Subject: ADV: Are you protected? Free Life Insurance quote oefik
Date: Wed, 25 Sep 2002 09:47:00 -0400
Return-Path: <firstever001@top10.bestoffersonthenet.com>

--- Header Analysis Findings ---
- Return-Path found
- 4 Received headers detected
- No SPF/DKIM/DMARC authentication results present

--- ML Detection Results ---
Kaggle: Phishing | Score: 0.5059001445770264
SpamAssassin: Legitimate | Score: 0.4960792362689972
Trap4Phish: Legitimate | Score: 0.49498695135116577

--- Final Verdict ---
Suspicious / Potential Phishing

==============================
Testing file: 0015.1b871d654560011a0aaa29bb4e9054f7
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

--- Parsed Email Details ---
From: approvals@mindspring.com
To: Valued.Recipient@webnote.net
Subject: MSNBC: Rates Hit 35 year Low 4.75% ...12304
Date: Thu, 22 Aug 2002 20:49:30 -1800
Return-Path: <approvals@mindspring.com>

--- Header Analysis Findings ---
- Return-Path found
- 4 Received headers detected
- No SPF/DKIM/DMARC authentication results present

--- ML Detection Results ---
Kaggle: Phishing | Score: 0.5060584545135498
SpamAssassin: Legitimate | Score: 0.49436646699905396
Trap4Phish: Legitimate | Score: 0.49498695135116577

--- Final Verdict ---
Suspicious / Potential Phishing

In [ ]:
trap_df.head(1).T

                                                       0
file_name                        benign_sample_3253.xlsx
entropy_of_text                                 5.746068
macro_chr_count                                       39
macro_vocab_size                                   10079
macro_arithmetic_operator_count                     4759
macro_token_count                                  10079
macro_max_line_length                                 38
remote_template_present                                1
numeric_cell_count                                  4336
string_cell_count                                   8926
avg_cell_length                                11.184588
label                                                  0

In [ ]:
ham_folder = "Datasets/spamassassin/20021010_easy_ham/easy_ham"

import os
print("Total legitimate emails:", len(os.listdir(ham_folder)))

Total legitimate emails: 2551

In [ ]:
ham_files = os.listdir(ham_folder)[:5]

for file in ham_files:
    print("\n==============================")
    print("Testing file:", file)

    email_path = os.path.join(ham_folder, file)

    with open(email_path, "r", encoding="latin-1") as f:
        raw_email = f.read()

    generate_integrated_report(raw_email, sample_feature)

==============================
Testing file: 1916.de9bd1f5764cf1615cfdfa0d7ecffeb1

NameError: name 'sample_feature' is not defined

In [ ]:
ham_files = os.listdir(ham_folder)[:5]

legit_count = 0
phish_count = 0

for file in ham_files:
    email_path = os.path.join(ham_folder, file)

    with open(email_path, "r", encoding="latin-1") as f:
        raw_email = f.read()

    result = generate_integrated_report(raw_email, sample_features)

    if result["final_verdict"] == "Legitimate":
        legit_count += 1
    else:
        phish_count += 1

print("Legitimate:", legit_count)
print("Suspicious:", phish_count)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'gkm@petting-zoo.net', 'to': '0xdeadbeef@petting-zoo.net', 'subject': "New $199 PC Doesn't Do Windows", 'date': 'Wed, 02 Oct 2002 19:06:58 -0700', 'return_path': '<0xdeadbeef-request@petting-zoo.net>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby jmason.org (Postfix) with ESMTP id 3592216F03\tfor <jm@localhost>; Thu,  3 Oct 2002 12:22:47 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor jm@localhost (single-drop); Thu, 03 Oct 2002 12:22:47 +0100 (IST)', 'from petting-zoo.net (IDENT:postfix@petting-zoo.net    [64.166.12.219]) by dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id    g9326sK10458 for <jm-deadbeef@jmason.org>; Thu, 3 Oct 2002 03:06:54 +0100', 'by petting-zoo.net (Postfix, from userid 1004) id 42441EA2E;    Wed,  2 Oct 2002 19:07:00 -0700 (PDT)', 'from petting-zoo.net (localhost [127.0.0.1]) by petting-zoo.net    (Postfix) with ESMTP id 21672EA0A; Wed,  2 Oct 2002 19:06:58 -0700 (PDT)'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '5 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': "Forwarded-by: Monty Solomon New $199 PC Doesn't Do Windows\n     - Oct 2, 2002 03:53 PM (AP Online)\n     - http://finance.lycos.com/home/news/story.asp?story=28928829\n\nBy MATTHEW FORDAHL\nAP Technology Writer\n  \n  It's been about 20 years since a new Atari 400 or Commodore Vic\n20 could be had for less than $200. Even then, those relics were\nwell on their way from bargain bins to the dust bin of PC history.\n  Since then, few if any new computers have sold for less than\n$200. Any that did were seriously outdated or inoperable.\n  Now, in a challenge to established tech giants, several upstarts\nhave banded together to create a PC that retails for $199.86.\n  It doesn't do Windows. In fact, it doesn't do a lot of things.\n  The Microtel SYSMAR710, sold only at Wal-Mart's online store,\nruns on a Linux operating system variant called Lindows, which has\nbeen hyped as a new choice for consumers who want to break away\nfrom the Microsoft monopoly.\n\n...\n\n     - http://finance.lycos.com/home/news/story.asp?story=28928829", 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5018534064292908}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Spam/Phishing', 'confidence_score': 0.5006189346313477}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Suspicious / Potential Phishing'}

Final Verdict:
Suspicious / Potential Phishing
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'Rohit Khare <khare@alumni.caltech.edu>', 'to': 'fork@example.com', 'subject': 'InfoWorld profile of Max Levchin', 'date': 'Tue, 03 Sep 2002 14:35:48 -0700', 'return_path': '<fork-admin@xent.com>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby jmason.org (Postfix) with ESMTP id D9B4916F7A\tfor <jm@localhost>; Wed,  4 Sep 2002 11:40:00 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor jm@localhost (single-drop); Wed, 04 Sep 2002 11:40:00 +0100 (IST)', 'from xent.com ([64.161.22.236]) by dogma.slashnull.org    (8.11.6/8.11.6) with ESMTP id g83LawZ04243 for <jm@jmason.org>;    Tue, 3 Sep 2002 22:36:58 +0100', 'from lair.xent.com (localhost [127.0.0.1]) by xent.com (Postfix)    with ESMTP id A0104294108; Tue,  3 Sep 2002 14:34:02 -0700 (PDT)', 'from alumnus.caltech.edu (alumnus.caltech.edu [131.215.49.51])    by xent.com (Postfix) with ESMTP id D675F294099; Tue,  3 Sep 2002 14:33:22    -0700 (PDT)', 'from localhost (localhost [127.0.0.1]) by alumnus.caltech.edu    (8.12.3/8.12.3) with ESMTP id g83LZnfw010916; Tue, 3 Sep 2002 14:35:50    -0700 (PDT)'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '6 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': 'Congrats, in the end...\n> "If they didn\'t have Max, they might have succumbed, because PayPal was \n> susceptible to fraud and money laundering, and Max tightened them up,"\n\nhttp://www.infoworld.com/articles/ct/xml/02/09/02/020902ctspotlight.xml\n\nSecure and at ease\nBy\xa0Jack Mccarthy\nAugust 30, 2002 1:01 pm PT\n\nMAX LEVCHIN\'S FASCINATION with encryption started when he was a teenager \nin Kiev, Ukraine, and continued as he immigrated to the United States \nwhere he attended the University of Illinois at Urbana-Champaign. In \nlate 1998, not two years out of college, he drew on his passion to \nco-found PayPal, the online payment system that has since attracted tens \nof millions of users and gained the reputation as the premier Internet \ntransaction processor. Now online auction house eBay has acquired his \ncompany for a king\'s ransom.\n\nNot bad for a 27-year-old kid from Ukraine.\n\nA programmer since he was 10 years old, Levchin and his family moved to \nChicago in 1991, and since then he has pursued security as if on a \nmission. He created a startup right out of college to build secure \npasswords for Palm Pilots. He met Peter Thiel, and the two founded \nPayPal to target online payment security. Thiel is now CEO of the \ncompany.\n\n"This company was founded on the notion of security value," Levchin \nsays. "Peter Thiel and I shared that vision from the very beginning."\n\nThiel concentrates on company business matters, whereas Levchin remains \nfocused on security, which he says is the key to the company\'s good \nfortune.\n\n"I explain [PayPal] as a security company posing as a transaction \nprocessor," Levchin says. "We spend a lot of time designing security so \nit doesn\'t step on the toes of convenience and not the other way around. \nThe trade-off is fundamental."\n\nMountain View, Calif.-based PayPal allows businesses and consumers with \ne-mail addresses to send and receive payments via the Internet, \naccepting credit card or bank account payments for purchases. The \nservice extends to 38 countries, with more than 17 million users and \nmore than 3 million business accounts.\n\nMost of PayPal\'s users are participants in online auctions, which led \nPayPal to be closely linked with eBay, the leading Web auction site. \nAlthough they were once rivals, the relationship between the two \ncompanies resulted July 8 in eBay\'s tentative $1.5 billion acquisition \nof PayPal. The agreement is subject to regulatory review.\n\nLevchin says he will stay at PayPal as it merges with eBay. "There are \nareas of synergy and collaboration we can explore."\n\nAlthough security is a dominant feature for PayPal, the company\'s \nability to carry out open communications among the millions of \nparticipants fits the growing Web services model, Levchin says.\n\n"This is a service that links people and allows them to send messages to \none another," he says. Levchin is a panelist at InfoWorld\'s \nNext-Generation Web Services II conference Sept. 20\n\nPayPal, as an online payment system, is a natural target for fraud. And \nLevchin has almost singlehandedly saved the company from thieves bent on \nexploiting the system, says Avivah Litan, a vice president and analyst \ncovering financial services at Stamford, Conn.-based Gartner.\n\n"If they didn\'t have Max, they might have succumbed, because PayPal was \nsusceptible to fraud and money laundering, and Max tightened them up," \nLitan says.\n\nTo combat criminals, Levchin established "Igor," an antifraud program \nthat monitors transactions and warns of suspicious accounts. Levchin \nsays building security and antifraud systems is a job he relishes. "The \nwork I do is important to PayPal and to consumers in general because the \nwork makes Internet shopping safe. It\'s the view that ecommerce has \narrived."', 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5041226148605347}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.49732381105422974}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Suspicious / Potential Phishing'}

Final Verdict:
Suspicious / Potential Phishing
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'gkm@petting-zoo.net', 'to': '0xdeadbeef@petting-zoo.net', 'subject': 'Promises.', 'date': 'Fri, 30 Aug 2002 15:41:47 -0700', 'return_path': '<0xdeadbeef-request@petting-zoo.net>', 'received_headers': ['from localhost (localhost [127.0.0.1])\tby phobos.labs.netnoteinc.com (Postfix) with ESMTP id 679CA43F9B\tfor <zzzz@localhost>; Mon,  2 Sep 2002 07:31:09 -0400 (EDT)', 'from phobos [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Mon, 02 Sep 2002 12:31:09 +0100 (IST)', 'from petting-zoo.net (petting-zoo.net [64.166.12.219]) by    dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g7UMh7Z10885 for    <zzzz-deadbeef@example.com>; Fri, 30 Aug 2002 23:43:08 +0100', 'by petting-zoo.net (Postfix, from userid 1004) id 6770BEA3D;    Fri, 30 Aug 2002 15:42:18 -0700 (PDT)', 'from petting-zoo.net (localhost [127.0.0.1]) by petting-zoo.net    (Postfix) with ESMTP id 53DEBEA0A for <0xdeadbeef@petting-zoo.net>;    Fri, 30 Aug 2002 15:42:07 -0700 (PDT)'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '5 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': 'Forwarded-by: Rob Windsor Forwarded-by: "Shirley Baer"\nForwarded-by: cjw59068\nForwarded-by: Joe & Allie Greenough\n\nThere were four buddies golfing and the first guy said, "I had to\npromise my wife that I would paint the whole outside of the house\njust to go golfing."\n\nThe second guy said, "I promised my wife that I would remodel the\nkitchen for her."\n\nThe third guy said, "You guys have it easy! I promised my wife that\nI would build her a new deck." They continued to play the hole.\nThen the first guy said to the fourth guy, "What did you have to\npromise your wife?"\n\nThe fourth guy replied, "I didn\'t promise anything." All the guys\nwere shocked, "How did you do it?!" He replied, "It\'s simple. I\nset the alarm clock for 5:30. Then I poked my wife and asked, \'Golf\ncourse or intercourse?\' And she said, \'Wear your sweater.\'"', 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.503618597984314}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.4995023012161255}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Suspicious / Potential Phishing'}

Final Verdict:
Suspicious / Potential Phishing
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'Chuck Murcko <chuck@topsail.org>', 'to': 'Russell Turpin <deafbox@hotmail.com>', 'subject': "Re: Hanson's Sept 11 message in the National Review", 'date': 'Thu, 19 Sep 2002 11:01:49 -0700', 'return_path': '<fork-admin@xent.com>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby jmason.org (Postfix) with ESMTP id 1808416F03\tfor <jm@localhost>; Fri, 20 Sep 2002 11:32:34 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor jm@localhost (single-drop); Fri, 20 Sep 2002 11:32:35 +0100 (IST)', 'from xent.com ([64.161.22.236]) by dogma.slashnull.org    (8.11.6/8.11.6) with ESMTP id g8JI2hC31074 for <jm@jmason.org>;    Thu, 19 Sep 2002 19:02:43 +0100', 'from lair.xent.com (localhost [127.0.0.1]) by xent.com (Postfix)    with ESMTP id 9B2CC294162; Thu, 19 Sep 2002 10:59:05 -0700 (PDT)', 'from hughes-fe01.direcway.com (hughes-fe01.direcway.com    [66.82.20.91]) by xent.com (Postfix) with ESMTP id AC28329409C for    <fork@xent.com>; Thu, 19 Sep 2002 10:58:50 -0700 (PDT)', 'from spinnaker ([64.157.35.6]) by hughes-fe01.direcway.com    (InterMail vK.4.04.00.00 201-232-137 license    dcc4e84cb8fc01ca8f8654c982ec8526) with ESMTP id    <20020919180238.RUXM977.hughes-fe01@spinnaker>; Thu, 19 Sep 2002 14:02:38    -0400'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '6 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': "What I meant was that neither he nor anyone else has any *authority* to \nsay something can or can't be published, and make that stick, at least \nin the US, and from some descriptions, France. Of course he can say \nanything he wants. And I can choose to ignore it, or not. Works both \nways.\n\nFscking semantics.\n\nChuck\n\nOn Thursday, September 19, 2002, at 06:41 AM, Russell Turpin wrote:\n\n> Robert Harley:\n>>> BTW, I wasn't aware that the 1st Amendment mandated that crap must be \n>>> FoRKed.\n>\n> Chuck Murcko :\n>> It doesn't, BTW. It says the right to free speech shall not be \n>> abridged. That means *you* can't say anything may not be FoRKed or \n>> printed or whatever.\n>\n> Actually, it means just the opposite. The first\n> amendment guarantees Harley's right to say just\n> that. For the outlets where he has editorial\n> control, it even guarantees his right to CENSOR\n> content published through those outlets. The\n> first amendment doesn't limit Harley's speech,\n> and it is neutral with regard to the selection\n> policies of FoRK and other private venues.\n>\n>\n>\n> _________________________________________________________________\n> MSN Photos is the easiest way to share and print your photos: \n> http://photos.msn.com/support/worldwide.aspx\n>", 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5000167489051819}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.49719005823135376}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Suspicious / Potential Phishing'}

Final Verdict:
Suspicious / Potential Phishing
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'scripting <rssfeeds@example.com>', 'to': 'yyyy@example.com', 'subject': "After posting my comment yesterday about next things I want to    do, I'm star", 'date': 'Tue, 24 Sep 2002 08:00:12 -0000', 'return_path': '<rssfeeds@example.com>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby jmason.org (Postfix) with ESMTP id 2115716F03\tfor <jm@localhost>; Tue, 24 Sep 2002 10:47:53 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor jm@localhost (single-drop); Tue, 24 Sep 2002 10:47:53 +0100 (IST)', 'from dogma.slashnull.org (localhost [127.0.0.1]) by    dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g8O80CC26584 for    <jm@jmason.org>; Tue, 24 Sep 2002 09:00:12 +0100'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '3 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': 'URL: http://scriptingnews.userland.com/backissues/2002/09/23#When:8:11:28AM\nDate: Mon, 23 Sep 2002 15:11:28 GMT\n\nAfter posting my comment yesterday about next things[1] I want to do, I\'m \nstarting to get job offers. Hey I wasn\'t expecting that. But I like it I like \nit. Especially in this stinkin economy. On the other hand can you imagine _me_ \nwith a job? ";->"\n\n[1] http://scriptingnews.userland.com/backissues/2002/09/22#whatsNextForDave', 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.502914309501648}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.4942915737628937}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Suspicious / Potential Phishing'}

Final Verdict:
Suspicious / Potential Phishing
Legitimate: 0
Suspicious: 5

In [ ]:
result = generate_integrated_report(raw_email, sample_features)

type(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'gkm@petting-zoo.net', 'to': '0xdeadbeef@petting-zoo.net', 'subject': "New $199 PC Doesn't Do Windows", 'date': 'Wed, 02 Oct 2002 19:06:58 -0700', 'return_path': '<0xdeadbeef-request@petting-zoo.net>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby jmason.org (Postfix) with ESMTP id 3592216F03\tfor <jm@localhost>; Thu,  3 Oct 2002 12:22:47 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor jm@localhost (single-drop); Thu, 03 Oct 2002 12:22:47 +0100 (IST)', 'from petting-zoo.net (IDENT:postfix@petting-zoo.net    [64.166.12.219]) by dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id    g9326sK10458 for <jm-deadbeef@jmason.org>; Thu, 3 Oct 2002 03:06:54 +0100', 'by petting-zoo.net (Postfix, from userid 1004) id 42441EA2E;    Wed,  2 Oct 2002 19:07:00 -0700 (PDT)', 'from petting-zoo.net (localhost [127.0.0.1]) by petting-zoo.net    (Postfix) with ESMTP id 21672EA0A; Wed,  2 Oct 2002 19:06:58 -0700 (PDT)'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '5 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': "Forwarded-by: Monty Solomon New $199 PC Doesn't Do Windows\n     - Oct 2, 2002 03:53 PM (AP Online)\n     - http://finance.lycos.com/home/news/story.asp?story=28928829\n\nBy MATTHEW FORDAHL\nAP Technology Writer\n  \n  It's been about 20 years since a new Atari 400 or Commodore Vic\n20 could be had for less than $200. Even then, those relics were\nwell on their way from bargain bins to the dust bin of PC history.\n  Since then, few if any new computers have sold for less than\n$200. Any that did were seriously outdated or inoperable.\n  Now, in a challenge to established tech giants, several upstarts\nhave banded together to create a PC that retails for $199.86.\n  It doesn't do Windows. In fact, it doesn't do a lot of things.\n  The Microtel SYSMAR710, sold only at Wal-Mart's online store,\nruns on a Linux operating system variant called Lindows, which has\nbeen hyped as a new choice for consumers who want to break away\nfrom the Microsoft monopoly.\n\n...\n\n     - http://finance.lycos.com/home/news/story.asp?story=28928829", 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5018534064292908}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Spam/Phishing', 'confidence_score': 0.5006189346313477}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Suspicious / Potential Phishing'}

Final Verdict:
Suspicious / Potential Phishing

dict

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [ ]:
test_results = []

def get_integrated_label(raw_email):
    result = generate_integrated_report(raw_email, sample_features)
    return result["final_verdict"]

# 10 spam emails
for file in os.listdir(spam_folder)[:10]:
    email_path = os.path.join(spam_folder, file)
    with open(email_path, "r", encoding="latin-1") as f:
        raw_email = f.read()

    pred = get_integrated_label(raw_email)
    test_results.append(["spam", pred])

# 10 legitimate emails
for file in os.listdir(ham_folder)[:10]:
    email_path = os.path.join(ham_folder, file)
    with open(email_path, "r", encoding="latin-1") as f:
        raw_email = f.read()

    pred = get_integrated_label(raw_email)
    test_results.append(["legitimate", pred])

test_results

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'sunday68@bluemail.dk', 'to': 'paulifree@hotmail.com', 'subject': 'FORTUNE 500 WORK AT HOME REPS NEEDED!', 'date': 'Fri, 20 Sep 2002 04:47:45 +0100', 'return_path': '<sunday68@bluemail.dk>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby zzzzason.org (Postfix) with ESMTP id 8FD3716F03\tfor <zzzz@localhost>; Fri, 20 Sep 2002 11:41:21 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Fri, 20 Sep 2002 11:41:21 +0100 (IST)', 'from webnote.net (mail.webnote.net [193.120.211.219]) by    dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g8K3lHC19280 for    <zzzz@jmason.org>; Fri, 20 Sep 2002 04:47:17 +0100', 'from bluemail.dk (host230-95.pool21756.interbusiness.it    [217.56.95.230]) by webnote.net (8.9.3/8.9.3) with SMTP id EAA04124;    Fri, 20 Sep 2002 04:47:45 +0100'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '4 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': 'Immediate Help Needed.  We are a fortune 500 company that is \ngrowing at a tremendous rate of over 1000% per year. We simply cannot \nkeep up. We are looking for motivated individuals who are looking to \nearn a substantial income working from home. \n\nThis is a real opportunity to make an excellent income from home. No \nexperience is required.  We will provide you with any training you may need. \n\nWe are looking for energetic and self motivated people.  If that is you \nthan click on the link below and complete our online information request \nform, \nand one of our employment specialist will contact you. \n\nhttp://ter.netblah.com:27000\n\nSo if you are looking to be employed at home, with a career that will \nprovide you vast opportunities and a substantial income, please fill \nout our online information request form here now: \n\nhttp://ter.netblah.com:27000\n\n\nTo be removed from our list simply click on the link below now: \n\nhttp://ter.netblah.com:27000\n\n1631Pl5', 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5032728314399719}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.4946371018886566}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'pamela4701@eudoramail.com', 'to': 'Undisclosed.Recipients@smtp-ft1.fr.colt.net', 'subject': 'Let us find the right mortgage lender for you      AFPE', 'date': 'Mon, 09 Sep 2002 14:36:18 -0700', 'return_path': '<pamela4701@eudoramail.com>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby zzzzason.org (Postfix) with ESMTP id 5D14216F17\tfor <zzzz@localhost>; Mon,  9 Sep 2002 10:49:04 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Mon, 09 Sep 2002 10:49:04 +0100 (IST)', 'from smtp-ft1.fr.colt.net (smtp-ft1.fr.colt.net [213.41.78.25])    by dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g899AfC06863 for    <webmaster@efi.ie>; Mon, 9 Sep 2002 10:10:41 +0100', 'from mailsweeper.abc-arbitrage.com (mailhost2.abc-arbitrage.com    [213.41.18.43]) by smtp-ft1.fr.colt.net with ESMTP id g899AvS20929 for    <webmaster@efi.ie>; Mon, 9 Sep 2002 11:10:57 +0200', 'from 210.214.94.76 (unverified) by mailsweeper.abc-arbitrage.com    (Content Technologies SMTPRS 4.2.10) with ESMTP id    <T5d3abf3ca1c0a8bf0537c@mailsweeper.abc-arbitrage.com>; Mon,    9 Sep 2002 11:06:09 +0200'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '5 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': 'Dear Homeowner,\n \nInterest Rates are at their lowest point in 40 years!\n\nWe help you find the best rate for your situation by\nmatching your needs with hundreds of lenders!\n\nHome Improvement, Refinance, Second Mortgage,\nHome Equity Loans, and More! Even with less than\nperfect credit!\n\nThis service is 100% FREE to home owners and new\nhome buyers without any obligation. \n\nJust fill out a quick, simple form and jump-start\nyour future plans today!\n\n\nVisit http://61.145.116.186/user0201/index.asp?Afft=QM10\n\n\n\n\n\n\nTo unsubscribe, please visit:\n\nhttp://61.145.116.186/light/watch.asp', 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Legitimate', 'confidence_score': 0.49938228726387024}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.4973808228969574}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'Free xxx movie <thisisagreatfreepornmovie@framesetup.com>', 'to': 'zzzz@example.com', 'subject': '60 minute free porn movie', 'date': 'Mon, 26 Aug 2002 22:18:15 -0400', 'return_path': '<thisisagreatfreepornmovie@framesetup.com>', 'received_headers': ['from localhost (localhost [127.0.0.1])\tby phobos.labs.example.com (Postfix) with ESMTP id 135B443F9B\tfor <zzzz@localhost>; Mon, 26 Aug 2002 20:34:09 -0400 (EDT)', 'from mail.webnote.net [193.120.211.219]\tby localhost with POP3 (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Tue, 27 Aug 2002 01:34:09 +0100 (IST)', 'from framesetup.com (1Cust182.tnt27.det3.da.uu.net [67.217.40.182])\tby webnote.net (8.9.3/8.9.3) with SMTP id BAA28619\tfor <zzzz@example.com>; Tue, 27 Aug 2002 01:31:58 +0100'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '3 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': 'Untitled Document Click \n  Here to enlarge your penis 3-4 inches naturally Click Here to be removed', 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5031223297119141}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.49444079399108887}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'firstever001@top10.bestoffersonthenet.com', 'to': 'yziubpzytm@top10.bestoffersonthenet.com', 'subject': 'ADV: Are you protected? Free Life Insurance quote oefik', 'date': 'Wed, 25 Sep 2002 09:47:00 -0400', 'return_path': '<firstever001@top10.bestoffersonthenet.com>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby zzzzason.org (Postfix) with ESMTP id 8706216F03\tfor <zzzz@localhost>; Thu, 26 Sep 2002 11:11:36 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Thu, 26 Sep 2002 11:11:36 +0100 (IST)', 'from webnote.net (mail.webnote.net [193.120.211.219]) by    dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g8PGjpC05018 for    <zzzz@jmason.org>; Wed, 25 Sep 2002 17:45:51 +0100', 'from top10.bestoffersonthenet.com ([64.25.38.250]) by    webnote.net (8.9.3/8.9.3) with ESMTP id RAA26647 for <zzzz@example.com>;    Wed, 25 Sep 2002 17:46:27 +0100'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '4 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': 'Lowest rates available for term life insurance! \n  \nTake a moment and fill out our online form to see the low rate you qualify for. \n  \nSave up to 70% from regular rates! \n  \nSmokers accepted! \n  \nhttp://ww1.bestoffersonthenet.com/termlifequote/\n            \nRepresenting quality nationwide carriers. Act now!\n         \n         \n         \n         \n          \n---------------------------------------\nTo easily remove your address from the list, go to: \nhttp://ww1.bestoffersonthenet.com/stopthemailplease/\nPlease allow 48-72 hours for removal.', 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5059001445770264}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.4960792362689972}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'approvals@mindspring.com', 'to': 'Valued.Recipient@webnote.net', 'subject': 'MSNBC: Rates Hit 35 year Low 4.75% ...12304', 'date': 'Thu, 22 Aug 2002 20:49:30 -1800', 'return_path': '<approvals@mindspring.com>', 'received_headers': ['from localhost (localhost [127.0.0.1])\tby phobos.labs.example.com (Postfix) with ESMTP id 28CA544159\tfor <zzzz@localhost>; Fri, 23 Aug 2002 06:02:53 -0400 (EDT)', 'from mail.webnote.net [193.120.211.219]\tby localhost with POP3 (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Fri, 23 Aug 2002 11:02:53 +0100 (IST)', 'from bmbgglawweb.bmbgglaw ([202.164.173.138])\tby webnote.net (8.9.3/8.9.3) with ESMTP id FAA08441\tfor <zzzz@example.com>; Fri, 23 Aug 2002 05:37:53 +0100', 'from smtp-gw-4.msn.com (200.173.221.83 [200.173.221.83]) by bmbgglawweb.bmbgglaw with SMTP (Microsoft Exchange Internet Mail Service Version 5.5.2653.13)\tid RMT9XDW1; Fri, 23 Aug 2002 10:55:23 +0800'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '4 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': "===================================================================\n\nNow you can have HUNDREDS of lenders compete for your loan!\n\nFACT: Interest Rates are at their lowest point in 40 years!\n\nYou're eligible even with less than perfect credit !!\n\n\t* Refinancing\n\t* New Home Loans\n\t* Debt Consolidation\n\t* Debt Consultation\n\t* Auto Loans\n\t* Credit Cards\n\t* Student Loans\n\t* Second Mortgage\n\t* Home Equity\n\nThis Service is 100% FREE without any obligation.\n\nVisit Our Web Site at:  http://marketing-fashion.com/user0201/index.asp?Afft=QM3\n\n====================================================================\n\nTo Unsubscribe: http://marketing-fashion.com/light/watch.asp", 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5060584545135498}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.49436646699905396}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'Trisha <TrishaRPotter@yahoo.co.uk>', 'to': '', 'subject': 'Congratulations on Your 6 New Signups', 'date': 'Tue, 24 Sep 2002 10:39:13 -0000', 'return_path': '<TrishaRPotter@yahoo.co.uk>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby zzzzason.org (Postfix) with ESMTP id 8636B16F03\tfor <zzzz@localhost>; Tue, 24 Sep 2002 17:57:55 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Tue, 24 Sep 2002 17:57:55 +0100 (IST)', 'from webnote.net (mail.webnote.net [193.120.211.219]) by    dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g8OFTdC09883 for    <zzzz@jmason.org>; Tue, 24 Sep 2002 16:29:39 +0100', 'from gateway.lauraandjoel.com (12-234-225-135.client.attbi.com    [12.234.225.135]) by webnote.net (8.9.3/8.9.3) with ESMTP id QAA19993 for    <zzzz@example.com>; Tue, 24 Sep 2002 16:30:13 +0100', 'from QRJATYDI ([200.47.195.200]) by gateway.lauraandjoel.com    (8.8.5/8.8.5) with SMTP id IAA03919; Tue, 24 Sep 2002 08:55:39 -0700 (PDT)'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '5 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': "We guarantee you signups before you ever pay\na penny!  We will show you the green before you\never take out your wallet.  Sign up for FREE and \ntest drive our system.  No Obligation whatsoever.  \nNo Time Limit on the test drive. Our system is so \npowerful that the system enrolled over 400 people \ninto my downline the first week.\n\nTo get signed up for FREE and take a test drive use \nthe link:\nmailto:workinathome@btamail.net.cn?subject=more_MOSS4_info_please\nBe sure to request info if the subject line does not! \n\nThe national attention drawn by this program \nwill drive this program with incredible momentum! \nDon't wait, if you wait, the next 400 people will \nbe above you.\n\nTake your FREE test drive and have the next 400  \nbelow you!\n\nmailto:workinathome@btamail.net.cn?subject=more_MOSS4_info_please\nBe sure to request info if the subject line does not! \n\nAll the best,\n\nDaniel\nFinancially Independent Home Business Owner\n\n\n\n\n\n______________________________________________________\nTo be excluded from future notices:\nmailto:guaranteed4u@btamail.net.cn?subject=exclude", 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5037003755569458}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.49892696738243103}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'zzzz@webnote.net', 'to': 'zzzz@example.com', 'subject': 'A better investment than the stock market.', 'date': 'Mon, 02 Sep 2002 02:56:26 -0500', 'return_path': '<zzzz@example.com>', 'received_headers': ['from localhost (localhost [127.0.0.1])\tby phobos.labs.example.com (Postfix) with ESMTP id 6731743F99\tfor <zzzz@localhost>; Mon,  2 Sep 2002 07:19:55 -0400 (EDT)', 'from mail.webnote.net [193.120.211.219]\tby localhost with POP3 (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Mon, 02 Sep 2002 12:19:55 +0100 (IST)', 'from smtp.easydns.com (smtp.easydns.com [205.210.42.30])\tby webnote.net (8.9.3/8.9.3) with ESMTP id HAA26244\tfor <zzzz@example.com>; Mon, 2 Sep 2002 07:52:05 +0100', 'from $domain (unknown [202.104.189.20])\tby smtp.easydns.com (Postfix) with SMTP id CD5752FD89\tfor <zzzz@example.com>; Mon,  2 Sep 2002 02:51:56 -0400 (EDT)', 'from example.com by PTOR0E7585NO3B.netnoteinc.com with SMTP for zzzz@netnoteinc.com; Mon, 02 Sep 2002 02:56:26 -0500'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '5 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:

[['spam', 'Likely Legitimate'],
 ['spam', 'Likely Legitimate'],
 ['spam', 'Likely Legitimate'],
 ['spam', 'Likely Legitimate'],
 ['spam', 'Likely Legitimate'],
 ['spam', 'Likely Legitimate'],
 ['spam', 'Likely Legitimate'],
 ['spam', 'Likely Legitimate'],
 ['spam', 'Likely Legitimate'],
 ['spam', 'Suspicious / Potential Phishing'],
 ['legitimate', 'Suspicious / Potential Phishing'],
 ['legitimate', 'Likely Legitimate'],
 ['legitimate', 'Likely Legitimate'],
 ['legitimate', 'Likely Legitimate'],
 ['legitimate', 'Likely Legitimate'],
 ['legitimate', 'Likely Legitimate'],
 ['legitimate', 'Likely Legitimate'],
 ['legitimate', 'Likely Legitimate'],
 ['legitimate', 'Likely Legitimate'],
 ['legitimate', 'Likely Legitimate']]

In [ ]:
model_test_results = []

for file in os.listdir(spam_folder)[:10]:
    path = os.path.join(spam_folder, file)
    with open(path, "r", encoding="latin-1") as f:
        raw_email = f.read()
    body = clean_email_body(raw_email)

    kag = predict_kaggle_email(body)["prediction"]
    spam = predict_spamassassin_email(body)["prediction"]

    model_test_results.append(["spam", kag, spam])

for file in os.listdir(ham_folder)[:10]:
    path = os.path.join(ham_folder, file)
    with open(path, "r", encoding="latin-1") as f:
        raw_email = f.read()
    body = clean_email_body(raw_email)

    kag = predict_kaggle_email(body)["prediction"]
    spam = predict_spamassassin_email(body)["prediction"]

    model_test_results.append(["legitimate", kag, spam])

model_test_results

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step

[['spam', 'Phishing', 'Legitimate'],
 ['spam', 'Legitimate', 'Legitimate'],
 ['spam', 'Phishing', 'Legitimate'],
 ['spam', 'Phishing', 'Legitimate'],
 ['spam', 'Phishing', 'Legitimate'],
 ['spam', 'Phishing', 'Legitimate'],
 ['spam', 'Legitimate', 'Legitimate'],
 ['spam', 'Phishing', 'Legitimate'],
 ['spam', 'Legitimate', 'Spam/Phishing'],
 ['spam', 'Phishing', 'Spam/Phishing'],
 ['legitimate', 'Phishing', 'Spam/Phishing'],
 ['legitimate', 'Phishing', 'Legitimate'],
 ['legitimate', 'Phishing', 'Legitimate'],
 ['legitimate', 'Phishing', 'Legitimate'],
 ['legitimate', 'Phishing', 'Legitimate'],
 ['legitimate', 'Legitimate', 'Spam/Phishing'],
 ['legitimate', 'Phishing', 'Legitimate'],
 ['legitimate', 'Phishing', 'Legitimate'],
 ['legitimate', 'Phishing', 'Legitimate'],
 ['legitimate', 'Legitimate', 'Legitimate']]

In [ ]:
import pandas as pd
results_df = pd.DataFrame(
    model_test_results,
    columns=["Actual", "Kaggle", "SpamAssassin"]
)
results_df.head()

  Actual      Kaggle SpamAssassin
0   spam    Phishing   Legitimate
1   spam  Legitimate   Legitimate
2   spam    Phishing   Legitimate
3   spam    Phishing   Legitimate
4   spam    Phishing   Legitimate

In [ ]:
results_df

        Actual      Kaggle   SpamAssassin
0         spam    Phishing     Legitimate
1         spam  Legitimate     Legitimate
2         spam    Phishing     Legitimate
3         spam    Phishing     Legitimate
4         spam    Phishing     Legitimate
5         spam    Phishing     Legitimate
6         spam  Legitimate     Legitimate
7         spam    Phishing     Legitimate
8         spam  Legitimate  Spam/Phishing
9         spam    Phishing  Spam/Phishing
10  legitimate    Phishing  Spam/Phishing
11  legitimate    Phishing     Legitimate
12  legitimate    Phishing     Legitimate
13  legitimate    Phishing     Legitimate
14  legitimate    Phishing     Legitimate
15  legitimate  Legitimate  Spam/Phishing
16  legitimate    Phishing     Legitimate
17  legitimate    Phishing     Legitimate
18  legitimate    Phishing     Legitimate
19  legitimate  Legitimate     Legitimate

In [ ]:
from sklearn.metrics import accuracy_score

kaggle_correct = (
    ((results_df["Actual"] == "spam") & (results_df["Kaggle"] == "Phishing")) |
    ((results_df["Actual"] == "legitimate") & (results_df["Kaggle"] == "Legitimate"))
)

spam_correct = (
    ((results_df["Actual"] == "spam") & (results_df["SpamAssassin"] == "Spam/Phishing")) |
    ((results_df["Actual"] == "legitimate") & (results_df["SpamAssassin"] == "Legitimate"))
)

print("Kaggle Accuracy:", kaggle_correct.mean())
print("SpamAssassin Accuracy:", spam_correct.mean())

Kaggle Accuracy: 0.45
SpamAssassin Accuracy: 0.5

In [ ]:
len(results_df)

20

In [ ]:
results = []

spam_files = os.listdir(spam_folder)[:100]
ham_files = os.listdir(ham_folder)[:100]

for file in spam_files:
    email_path = os.path.join(spam_folder, file)

    with open(email_path, "r", encoding="latin-1") as f:
        raw_email = f.read()

    result = generate_integrated_report(raw_email, sample_features)

    results.append(["spam", result["final_verdict"]])

for file in ham_files:
    email_path = os.path.join(ham_folder, file)

    with open(email_path, "r", encoding="latin-1") as f:
        raw_email = f.read()

    result = generate_integrated_report(raw_email, sample_features)

    results.append(["legitimate", result["final_verdict"]])

results_df = pd.DataFrame(results, columns=["Actual", "Prediction"])

results_df.head()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'sunday68@bluemail.dk', 'to': 'paulifree@hotmail.com', 'subject': 'FORTUNE 500 WORK AT HOME REPS NEEDED!', 'date': 'Fri, 20 Sep 2002 04:47:45 +0100', 'return_path': '<sunday68@bluemail.dk>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby zzzzason.org (Postfix) with ESMTP id 8FD3716F03\tfor <zzzz@localhost>; Fri, 20 Sep 2002 11:41:21 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Fri, 20 Sep 2002 11:41:21 +0100 (IST)', 'from webnote.net (mail.webnote.net [193.120.211.219]) by    dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g8K3lHC19280 for    <zzzz@jmason.org>; Fri, 20 Sep 2002 04:47:17 +0100', 'from bluemail.dk (host230-95.pool21756.interbusiness.it    [217.56.95.230]) by webnote.net (8.9.3/8.9.3) with SMTP id EAA04124;    Fri, 20 Sep 2002 04:47:45 +0100'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '4 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': 'Immediate Help Needed.  We are a fortune 500 company that is \ngrowing at a tremendous rate of over 1000% per year. We simply cannot \nkeep up. We are looking for motivated individuals who are looking to \nearn a substantial income working from home. \n\nThis is a real opportunity to make an excellent income from home. No \nexperience is required.  We will provide you with any training you may need. \n\nWe are looking for energetic and self motivated people.  If that is you \nthan click on the link below and complete our online information request \nform, \nand one of our employment specialist will contact you. \n\nhttp://ter.netblah.com:27000\n\nSo if you are looking to be employed at home, with a career that will \nprovide you vast opportunities and a substantial income, please fill \nout our online information request form here now: \n\nhttp://ter.netblah.com:27000\n\n\nTo be removed from our list simply click on the link below now: \n\nhttp://ter.netblah.com:27000\n\n1631Pl5', 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5032728314399719}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.4946371018886566}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'pamela4701@eudoramail.com', 'to': 'Undisclosed.Recipients@smtp-ft1.fr.colt.net', 'subject': 'Let us find the right mortgage lender for you      AFPE', 'date': 'Mon, 09 Sep 2002 14:36:18 -0700', 'return_path': '<pamela4701@eudoramail.com>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby zzzzason.org (Postfix) with ESMTP id 5D14216F17\tfor <zzzz@localhost>; Mon,  9 Sep 2002 10:49:04 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Mon, 09 Sep 2002 10:49:04 +0100 (IST)', 'from smtp-ft1.fr.colt.net (smtp-ft1.fr.colt.net [213.41.78.25])    by dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g899AfC06863 for    <webmaster@efi.ie>; Mon, 9 Sep 2002 10:10:41 +0100', 'from mailsweeper.abc-arbitrage.com (mailhost2.abc-arbitrage.com    [213.41.18.43]) by smtp-ft1.fr.colt.net with ESMTP id g899AvS20929 for    <webmaster@efi.ie>; Mon, 9 Sep 2002 11:10:57 +0200', 'from 210.214.94.76 (unverified) by mailsweeper.abc-arbitrage.com    (Content Technologies SMTPRS 4.2.10) with ESMTP id    <T5d3abf3ca1c0a8bf0537c@mailsweeper.abc-arbitrage.com>; Mon,    9 Sep 2002 11:06:09 +0200'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '5 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': 'Dear Homeowner,\n \nInterest Rates are at their lowest point in 40 years!\n\nWe help you find the best rate for your situation by\nmatching your needs with hundreds of lenders!\n\nHome Improvement, Refinance, Second Mortgage,\nHome Equity Loans, and More! Even with less than\nperfect credit!\n\nThis service is 100% FREE to home owners and new\nhome buyers without any obligation. \n\nJust fill out a quick, simple form and jump-start\nyour future plans today!\n\n\nVisit http://61.145.116.186/user0201/index.asp?Afft=QM10\n\n\n\n\n\n\nTo unsubscribe, please visit:\n\nhttp://61.145.116.186/light/watch.asp', 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Legitimate', 'confidence_score': 0.49938228726387024}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.4973808228969574}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'Free xxx movie <thisisagreatfreepornmovie@framesetup.com>', 'to': 'zzzz@example.com', 'subject': '60 minute free porn movie', 'date': 'Mon, 26 Aug 2002 22:18:15 -0400', 'return_path': '<thisisagreatfreepornmovie@framesetup.com>', 'received_headers': ['from localhost (localhost [127.0.0.1])\tby phobos.labs.example.com (Postfix) with ESMTP id 135B443F9B\tfor <zzzz@localhost>; Mon, 26 Aug 2002 20:34:09 -0400 (EDT)', 'from mail.webnote.net [193.120.211.219]\tby localhost with POP3 (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Tue, 27 Aug 2002 01:34:09 +0100 (IST)', 'from framesetup.com (1Cust182.tnt27.det3.da.uu.net [67.217.40.182])\tby webnote.net (8.9.3/8.9.3) with SMTP id BAA28619\tfor <zzzz@example.com>; Tue, 27 Aug 2002 01:31:58 +0100'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '3 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': 'Untitled Document Click \n  Here to enlarge your penis 3-4 inches naturally Click Here to be removed', 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5031223297119141}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.49444079399108887}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'firstever001@top10.bestoffersonthenet.com', 'to': 'yziubpzytm@top10.bestoffersonthenet.com', 'subject': 'ADV: Are you protected? Free Life Insurance quote oefik', 'date': 'Wed, 25 Sep 2002 09:47:00 -0400', 'return_path': '<firstever001@top10.bestoffersonthenet.com>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby zzzzason.org (Postfix) with ESMTP id 8706216F03\tfor <zzzz@localhost>; Thu, 26 Sep 2002 11:11:36 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Thu, 26 Sep 2002 11:11:36 +0100 (IST)', 'from webnote.net (mail.webnote.net [193.120.211.219]) by    dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g8PGjpC05018 for    <zzzz@jmason.org>; Wed, 25 Sep 2002 17:45:51 +0100', 'from top10.bestoffersonthenet.com ([64.25.38.250]) by    webnote.net (8.9.3/8.9.3) with ESMTP id RAA26647 for <zzzz@example.com>;    Wed, 25 Sep 2002 17:46:27 +0100'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '4 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': 'Lowest rates available for term life insurance! \n  \nTake a moment and fill out our online form to see the low rate you qualify for. \n  \nSave up to 70% from regular rates! \n  \nSmokers accepted! \n  \nhttp://ww1.bestoffersonthenet.com/termlifequote/\n            \nRepresenting quality nationwide carriers. Act now!\n         \n         \n         \n         \n          \n---------------------------------------\nTo easily remove your address from the list, go to: \nhttp://ww1.bestoffersonthenet.com/stopthemailplease/\nPlease allow 48-72 hours for removal.', 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5059001445770264}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.4960792362689972}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'approvals@mindspring.com', 'to': 'Valued.Recipient@webnote.net', 'subject': 'MSNBC: Rates Hit 35 year Low 4.75% ...12304', 'date': 'Thu, 22 Aug 2002 20:49:30 -1800', 'return_path': '<approvals@mindspring.com>', 'received_headers': ['from localhost (localhost [127.0.0.1])\tby phobos.labs.example.com (Postfix) with ESMTP id 28CA544159\tfor <zzzz@localhost>; Fri, 23 Aug 2002 06:02:53 -0400 (EDT)', 'from mail.webnote.net [193.120.211.219]\tby localhost with POP3 (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Fri, 23 Aug 2002 11:02:53 +0100 (IST)', 'from bmbgglawweb.bmbgglaw ([202.164.173.138])\tby webnote.net (8.9.3/8.9.3) with ESMTP id FAA08441\tfor <zzzz@example.com>; Fri, 23 Aug 2002 05:37:53 +0100', 'from smtp-gw-4.msn.com (200.173.221.83 [200.173.221.83]) by bmbgglawweb.bmbgglaw with SMTP (Microsoft Exchange Internet Mail Service Version 5.5.2653.13)\tid RMT9XDW1; Fri, 23 Aug 2002 10:55:23 +0800'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '4 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': "===================================================================\n\nNow you can have HUNDREDS of lenders compete for your loan!\n\nFACT: Interest Rates are at their lowest point in 40 years!\n\nYou're eligible even with less than perfect credit !!\n\n\t* Refinancing\n\t* New Home Loans\n\t* Debt Consolidation\n\t* Debt Consultation\n\t* Auto Loans\n\t* Credit Cards\n\t* Student Loans\n\t* Second Mortgage\n\t* Home Equity\n\nThis Service is 100% FREE without any obligation.\n\nVisit Our Web Site at:  http://marketing-fashion.com/user0201/index.asp?Afft=QM3\n\n====================================================================\n\nTo Unsubscribe: http://marketing-fashion.com/light/watch.asp", 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5060584545135498}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.49436646699905396}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'Trisha <TrishaRPotter@yahoo.co.uk>', 'to': '', 'subject': 'Congratulations on Your 6 New Signups', 'date': 'Tue, 24 Sep 2002 10:39:13 -0000', 'return_path': '<TrishaRPotter@yahoo.co.uk>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby zzzzason.org (Postfix) with ESMTP id 8636B16F03\tfor <zzzz@localhost>; Tue, 24 Sep 2002 17:57:55 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Tue, 24 Sep 2002 17:57:55 +0100 (IST)', 'from webnote.net (mail.webnote.net [193.120.211.219]) by    dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g8OFTdC09883 for    <zzzz@jmason.org>; Tue, 24 Sep 2002 16:29:39 +0100', 'from gateway.lauraandjoel.com (12-234-225-135.client.attbi.com    [12.234.225.135]) by webnote.net (8.9.3/8.9.3) with ESMTP id QAA19993 for    <zzzz@example.com>; Tue, 24 Sep 2002 16:30:13 +0100', 'from QRJATYDI ([200.47.195.200]) by gateway.lauraandjoel.com    (8.8.5/8.8.5) with SMTP id IAA03919; Tue, 24 Sep 2002 08:55:39 -0700 (PDT)'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '5 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': "We guarantee you signups before you ever pay\na penny!  We will show you the green before you\never take out your wallet.  Sign up for FREE and \ntest drive our system.  No Obligation whatsoever.  \nNo Time Limit on the test drive. Our system is so \npowerful that the system enrolled over 400 people \ninto my downline the first week.\n\nTo get signed up for FREE and take a test drive use \nthe link:\nmailto:workinathome@btamail.net.cn?subject=more_MOSS4_info_please\nBe sure to request info if the subject line does not! \n\nThe national attention drawn by this program \nwill drive this program with incredible momentum! \nDon't wait, if you wait, the next 400 people will \nbe above you.\n\nTake your FREE test drive and have the next 400  \nbelow you!\n\nmailto:workinathome@btamail.net.cn?subject=more_MOSS4_info_please\nBe sure to request info if the subject line does not! \n\nAll the best,\n\nDaniel\nFinancially Independent Home Business Owner\n\n\n\n\n\n______________________________________________________\nTo be excluded from future notices:\nmailto:guaranteed4u@btamail.net.cn?subject=exclude", 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5037003755569458}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.49892696738243103}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'zzzz@webnote.net', 'to': 'zzzz@example.com', 'subject': 'A better investment than the stock market.', 'date': 'Mon, 02 Sep 2002 02:56:26 -0500', 'return_path': '<zzzz@example.com>', 'received_headers': ['from localhost (localhost [127.0.0.1])\tby phobos.labs.example.com (Postfix) with ESMTP id 6731743F99\tfor <zzzz@localhost>; Mon,  2 Sep 2002 07:19:55 -0400 (EDT)', 'from mail.webnote.net [193.120.211.219]\tby localhost with POP3 (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Mon, 02 Sep 2002 12:19:55 +0100 (IST)', 'from smtp.easydns.com (smtp.easydns.com [205.210.42.30])\tby webnote.net (8.9.3/8.9.3) with ESMTP id HAA26244\tfor <zzzz@example.com>; Mon, 2 Sep 2002 07:52:05 +0100', 'from $domain (unknown [202.104.189.20])\tby smtp.easydns.com (Postfix) with SMTP id CD5752FD89\tfor <zzzz@example.com>; Mon,  2 Sep 2002 02:51:56 -0400 (EDT)', 'from example.com by PTOR0E7585NO3B.netnoteinc.com with SMTP for zzzz@netnoteinc.com; Mon, 02 Sep 2002 02:56:26 -0500'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '5 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:

  Actual         Prediction
0   spam  Likely Legitimate
1   spam  Likely Legitimate
2   spam  Likely Legitimate
3   spam  Likely Legitimate
4   spam  Likely Legitimate

In [ ]:
kaggle_results = []

for file in os.listdir(spam_folder)[:100]:
    path = os.path.join(spam_folder, file)
    with open(path, "r", encoding="latin-1") as f:
        raw_email = f.read()

    body = clean_email_body(raw_email)
    pred = predict_kaggle_email(body)["prediction"]
    kaggle_results.append(["spam", pred])

for file in os.listdir(ham_folder)[:100]:
    path = os.path.join(ham_folder, file)
    with open(path, "r", encoding="latin-1") as f:
        raw_email = f.read()

    body = clean_email_body(raw_email)
    pred = predict_kaggle_email(body)["prediction"]
    kaggle_results.append(["legitimate", pred])

kaggle_df = pd.DataFrame(kaggle_results, columns=["Actual", "Prediction"])
kaggle_df.head()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step

  Actual  Prediction
0   spam    Phishing
1   spam  Legitimate
2   spam    Phishing
3   spam    Phishing
4   spam    Phishing

In [ ]:
kaggle_df["Prediction"].value_counts()

Prediction
Phishing      167
Legitimate     33
Name: count, dtype: int64

In [ ]:
pd.crosstab(kaggle_df["Actual"], kaggle_df["Prediction"])

Prediction  Legitimate  Phishing
Actual
legitimate          13        87
spam                20        80

In [ ]:
from sklearn.metrics import classification_report

y_true = ["Phishing" if x=="spam" else "Legitimate"
          for x in kaggle_df["Actual"]]

print(classification_report(
    y_true,
    kaggle_df["Prediction"]
))

              precision    recall  f1-score   support

  Legitimate       0.39      0.13      0.20       100
    Phishing       0.48      0.80      0.60       100

    accuracy                           0.47       200
   macro avg       0.44      0.47      0.40       200
weighted avg       0.44      0.47      0.40       200

In [75]:
generate_integrated_report(raw_email, sample_features)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step
====== INTEGRATED EMAIL FORENSIC REPORT ======

Parsed Email Details:
{'from': 'Answer.Us@davicom.co.kr', 'to': 'undisclosed-recipients:;', 'subject': '$10 a hour for watching e-mmercials! No joke!', 'date': 'Mon, 07 Oct 2002 22:57:45 -0400', 'return_path': '<bounce2@u-answer.com>', 'received_headers': ['from localhost (jalapeno [127.0.0.1])\tby zzzzason.org (Postfix) with ESMTP id 10C9616F18\tfor <zzzz@localhost>; Tue,  8 Oct 2002 11:02:05 +0100 (IST)', 'from jalapeno [127.0.0.1]\tby localhost with IMAP (fetchmail-5.9.0)\tfor zzzz@localhost (single-drop); Tue, 08 Oct 2002 11:02:05 +0100 (IST)', 'from webnote.net (mail.webnote.net [193.120.211.219]) by    dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g98339K30569 for    <zzzz@jmason.org>; Tue, 8 Oct 2002 04:03:10 +0100', 'from davicom.co.kr (IDENT:root@[211.205.76.5]) by webnote.net    (8.9.3/8.9.3) with ESMTP id EAA21173 for <zzzz@example.com>;    Tue, 8 Oct 2002 04:03:55 +0100', 'from u-answer.com (kenny.answer-us.com [12.43.213.7]) by    davicom.co.kr (v3smtp 8.11.2 Copyright (c) 1998-2000 Sendmail,    Inc.  All rights reserved. Copyright (c) 1988, 1993 The Regents of the    University of California.  All rights reserved./8.11.3) with ESMTP id    g983Hsn28746; Tue, 8 Oct 2002 12:17:55 +0900'], 'authentication_results': None}

Header Analysis Findings:
['Return-Path found', '5 Received headers detected', 'No SPF/DKIM/DMARC authentication results present']

ML Detection Results:
{'email_text': 'Answer-Us Unlist Information This message is brought to you by Answer-us.com in \n\t\tcompliance with current federal laws. To find out more about Answer-us.com visit http://www.answer-us.com . \n        You are receiving this mailing because you or someone you know has \n        registered this email address to receive special offers from an Answer-us.com \n        marketing partner. Screening of addresses has been done to the best of \n        our knowledge. We honor all unlist requests within 72 hours. If you\n        have received this email in error, we apologize for any inconvenience it \n        has caused and will not mail further offers to you. To be\n        unlisted from our database, please do the \n        following: Simply click here . If you have your mail forwarded to a new email address \n        please provide your old email address. A nswer - Us Nationwide support@answer-us.com Our \n        E-Mail Campaigns Have Produced\n      Staggering Response Rates! Responsive \n      General or Targeted Managed E-Mail Lists Visit www.answer-us.com today! Copyright \n        � 2002 Answer-us.com. All rights reserved.', 'kaggle_model_result': {'model': 'Kaggle Phishing Model', 'prediction': 'Phishing', 'confidence_score': 0.5053941607475281}, 'spamassassin_model_result': {'model': 'SpamAssassin Model', 'prediction': 'Legitimate', 'confidence_score': 0.49671536684036255}, 'trap4phish_model_result': {'model': 'Trap4Phish Model', 'prediction': 'Legitimate', 'confidence_score': 0.49498695135116577}, 'final_verdict': 'Likely Legitimate'}

Final Verdict:
Likely Legitimate

{'email_text': 'Answer-Us Unlist Information This message is brought to you by Answer-us.com in \n\t\tcompliance with current federal laws. To find out more about Answer-us.com visit http://www.answer-us.com . \n        You are receiving this mailing because you or someone you know has \n        registered this email address to receive special offers from an Answer-us.com \n        marketing partner. Screening of addresses has been done to the best of \n        our knowledge. We honor all unlist requests within 72 hours. If you\n        have received this email in error, we apologize for any inconvenience it \n        has caused and will not mail further offers to you. To be\n        unlisted from our database, please do the \n        following: Simply click here . If you have your mail forwarded to a new email address \n        please provide your old email address. A nswer - Us Nationwide support@answer-us.com Our \n        E-Mail Campaigns Have Produced\n      Staggering Response Rates! Responsive \n      General or Targeted Managed E-Mail Lists Visit www.answer-us.com today! Copyright \n        � 2002 Answer-us.com. All rights reserved.',
 'kaggle_model_result': {'model': 'Kaggle Phishing Model',
  'prediction': 'Phishing',
  'confidence_score': 0.5053941607475281},
 'spamassassin_model_result': {'model': 'SpamAssassin Model',
  'prediction': 'Legitimate',
  'confidence_score': 0.49671536684036255},
 'trap4phish_model_result': {'model': 'Trap4Phish Model',
  'prediction': 'Legitimate',
  'confidence_score': 0.49498695135116577},
 'final_verdict': 'Likely Legitimate'}